name: Maven Job
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    # permissions:
    #   id-token: write
    #   contents: read
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4.1.2
      - name: Clean and Package with Maven
        run: mvn clean package
      - name: Show target folder
        run: docker info
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to dockerhub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: kammana/wsapp:0.0.1
      
