name: Maven Job
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4.1.2
      - name: Set up JDK 11
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'jdk'
          
      - name: Maven Build
        uses: hb0730/maven-action@v1.0.2
      
